name: Feature request
description: Suggest an idea for this project
labels: [feature request, needs triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping to make RacoAndroid better by suggesting a feature.
        
  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I have checked and there are *no existing issues* - [open](https://github.com/hegocre/RacoAndroid/issues) or [closed](https://github.com/hegocre/RacoAndroid/issues?q=is%3Aissue+is%3Aclosed) - which request the same feature."
          required: true
        - label: "I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise."
          required: true
        - label: "This issue contains only one feature request."
          required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: |
        Explain how you want the app's look or behavior to change to suit your needs.
    validations:
      required: true

  - type: textarea
    id: why-is-the-feature-requested
    attributes:
      label: Why do you want this feature?
      description: |
        Describe any problem or limitation you come across while using the app which would be solved by this feature.
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Any other information you'd like to include, for instance sketches, mockups, pictures of cats, etc.
