package com.yara.raco.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF00629D)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFCFE5FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D33)
val md_theme_light_secondary = Color(0xFF695F00)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFAE500)
val md_theme_light_onSecondaryContainer = Color(0xFF1F1C00)
val md_theme_light_tertiary = Color(0xFF006783)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBCE9FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001F29)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFCFF)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFCFCFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFDEE3EB)
val md_theme_light_onSurfaceVariant = Color(0xFF42474E)
val md_theme_light_outline = Color(0xFF72777F)
val md_theme_light_inverseOnSurface = Color(0xFFF1F0F4)
val md_theme_light_inverseSurface = Color(0xFF2F3033)
val md_theme_light_inversePrimary = Color(0xFF98CBFF)

val md_theme_dark_primary = Color(0xFF98CBFF)
val md_theme_dark_onPrimary = Color(0xFF003354)
val md_theme_dark_primaryContainer = Color(0xFF004A77)
val md_theme_dark_onPrimaryContainer = Color(0xFFCFE5FF)
val md_theme_dark_secondary = Color(0xFFDBC900)
val md_theme_dark_onSecondary = Color(0xFF363100)
val md_theme_dark_secondaryContainer = Color(0xFF4F4800)
val md_theme_dark_onSecondaryContainer = Color(0xFFFAE500)
val md_theme_dark_tertiary = Color(0xFF63D3FF)
val md_theme_dark_onTertiary = Color(0xFF003545)
val md_theme_dark_tertiaryContainer = Color(0xFF004D63)
val md_theme_dark_onTertiaryContainer = Color(0xFFBCE9FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C1E)
val md_theme_dark_onBackground = Color(0xFFE2E2E5)
val md_theme_dark_surface = Color(0xFF1A1C1E)
val md_theme_dark_onSurface = Color(0xFFE2E2E5)
val md_theme_dark_surfaceVariant = Color(0xFF42474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C7CF)
val md_theme_dark_outline = Color(0xFF8C9199)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E5)
val md_theme_dark_inversePrimary = Color(0xFF00629D)